### ISSUE TITLE
Some vaults seem to stay locked

### ISSUE THREAD

**Issue by VelvetAurora245** [LumiOfFrost/TrialChamberRestock#2]
Some non-ominous vaults seem to stay locked regardless of the mod's settings, I have set both the timer and key requirement increase to zero and I have vaults that don't want keys at all when other vaults in the same trial chamber (including ominous ones) work as intended.

Might be related to vaults having been opened before installing the mod but i'm unsure about it, as some vaults I know i've opened before but still accept keys with no trouble

I tested the mod on vaults that have been generated/opened for the first time after installing the mod, and these seem to work as intended.

**Comment by LumiOfFrost** [comment]
Yeah, vaults that have already been opened prior to install will stay locked. I'll try to find a fix in the next update.
