### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by iv8512** [LumiOfFrost/TrialChamberRestock#5]
Could the dependencies be listed on Modrinth? The mod is requiring modmenu 11.0.0-rc.2 or later to function when that mod itself says that it's not supported on the server side.

**Comment by TheRonGDD** [comment]
Dependencies make this unusable for server side.

**Comment by LumiOfFrost** [comment]
Potentially fixed? May need to change stuff in the mod itself, modrinth dependencies are updated

**Comment by ZaksenCode** [comment]
So, i think this [pull request](https://github.com/LumiOfFrost/TrialChamberRestock/pull/6) should solve the problem

**Comment by LumiOfFrost** [comment]
Done. Will at some point build and release to modrinth/curseforge, at the moment my IDE isn't working.
